# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2e64379e163f7de6f602d2d3689929a841f74622cca2cd5e4ab1ffe826271fdc1b0b2dc56d856a39d7120f7c3a6990b658fd3116e29e32ece6bbed48b22c251

test:
  secret_key_base: c02e724dfa216e882186d68c05ed01948307d458436f7c931e467196efe6a8a6decebc5bd34cf24817623aea031777203cce2710a1c96f02c6f78f4144d833d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
