# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1257255ed0f858b4a20f80f313e443436537e00a916f1ba8f569ed35ce8bad0a9d56c195f33c1843947b3f06965dd70b86190a131e32047b93321e2b46e20fef

test:
  secret_key_base: dec7f2b9579a4404206099f95ea8522eefb102b640b1bb2ad90d0560ccc6f8fcf2fc80a28ffcdbb3c01613fe36a4beac6015c883260d0257a597d23875f78084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
